### PR TITLE
add personal webpages

### PR DESCRIPTION
**Pull request by zouharvi**
# Description

Related to  #247, this PR adds a few personal links (some were on request). Some people have multiple personal pages and in that case I tried to use the most "evergreen" one, which is usually the one they maintain themselves or that which is listed in their Google Scholar. I skipped multiple people because I don't know much about them and was unsure which to choose.

## Type of PR

- Edits `people/` by adding personal links where available. 

### Checklist:

- [x] I have read the [contributing guidelines](contributing.md).
- [x] I have followed the [style guide](http://machinetranslate.org/style).
- [x] I have made sure that the URL is not already in use.
- [x] I have cross-linked relevant articles.
- [x] I have used the UK spelling.
- [x] I have kept consistency with the structure of sister articles in the same directory.

### CODE REVIEW

**Comment by zouharvi** [comment]
This PR also adds Matt Post, a very influential researcher in MT.

Question: Currently the ordering is given by the number in the file header. Isn't there an easier way to e.g. sort them alphabetically?

**Comment by cefoo** [comment]
> Currently the ordering is given by the number in the file header. Isn't there an easier way to e.g. sort them alphabetically?

It's in inverse chronological birth order (may not be exact, I could not figure some exact birthdates out).

I should probably have spaced the ones we have better so that inserting new people is not too burdensome.
I'll work on that.

**Comment by zouharvi** [comment]
> It's in inverse chronological birth order (may not be exact, I could not figure some exact birthdates out).

I didn't know that and added Matt to the end of the list.

**Comment by cefoo** [comment]
Don't worry!

I'll fix the order (and space out the other People articles' nav order) after we merge.

**Comment by zouharvi** [comment]
Maybe this could also be discussed whether sorting by age is the best way for this? I understand that e.g. the "previous generation" should probably be shown at the bottom. But at the same time this doesn't feel entirely right for someone to get the spotlight just because they were born the latest.

**Comment by cefoo** [comment]
Sure, I agree! Should we move this to the discussion tab?

**Comment by zouharvi** [comment]
Alright. Could you merge this PR though? :slightly_smiling_face:

**Pull request merged**
