### PR TITLE
Add QE APIs support in Language pages

### LINKED ISSUE #548: Add QE APIs support in Language pages
If we currently go to any language page, we will see a section about its MT API support.
Example: [machinetranslate.org/spanish#api-support](https://machinetranslate.org/spanish#api-support)

Our current QE pages list supported languages.
Example: [machinetranslate.org/modelfront](https://machinetranslate.org/modelfront)

We now need to add QE support to language pages.
That way, pages like `spanish.md` will contain two support sections: API support and QE API support.

In order to make this structure more consistent with the rest of the website, we should follow the naming conventions from the `integrations.html` pages, like in [machinetranslate.org/memoq](https://machinetranslate.org/memoq).

In **Languages** pages...

`API support` should be renamed to `Machine translation`.
`QE API support` (doesn't exist in languages pages right now) should be named `Quality estimation`.

### PR DESCRIPTION
**Pull request by tovmasharrison**
# Description

I have added QE support to language pages, renamed the sections, and fixed the navbar for Languages to show child pages.

Now, each language page contains two support sections: Machine translation and Quality estimation.

Fixes #548 

### Checklist:

- [x] I have read the [contributing guidelines](contributing.md).
- [x] I have followed the [style guide](http://machinetranslate.org/style).

### CODE REVIEW

**Comment by cefoo** [comment]
Hi @tovmasharrison!

Thank you so much with your help in this issue! 🚀
It works well on my end! 

I just have two comments:

- We purposely omitted the language list on the menu. We figured the list is getting longer, and it would take the user too much time to scroll down and see the rest of the sections in the menu. What do you think?
- Maybe we can fix the wording here so that it is consistent between sections? (either by adding "**machine translation** APIs" or deleting "**quality estimation** APIs" and just leaving "APIs" alone.)

Screenshot 2023-10-19 at 09 17 37

**Comment by tovmasharrison** [comment]
Hi @cefoo!

Oh, my bad. I'll re-do the change on the languages bar. Also, I'll change the wording.

Thanks!

**Comment by cefoo** [comment]
Thanks, Tom!!

**Comment by tovmasharrison** [comment]
> Thanks, Tom!!

No problem!

**Review by bittlingmayer — APPROVED** [review]

**Pull request merged**
