### PR TITLE
Add Trados MT Enhanced plugin

### PR DESCRIPTION
**Pull request by martab0**
# Description

Fixes # _[Add the issue number]_

## Type of PR

- Creates the article _[article name]_
- Edits _[article name]_
- Other _[please describe]_

### Checklist:

- [ ] I have read the [contributing guidelines](contributing.md).
- [ ] I have followed the [style guide](http://machinetranslate.org/style).

### CODE REVIEW

**Comment by zouharvi** [comment]
What exactly is the `integrations.yml` file? Is it rendered somewhere on the website?

**Comment by martab0** [comment]
This is my small edit to Cecilia's branch :)

**Comment by zouharvi** [comment]
From my side I'd accept this immediately but I don't know the planned usage of this file so maybe @cefoo should make a decision here.

**Comment by martab0** [comment]
Yes, this is for @cefoo to accept or correct.

**Comment by cefoo** [comment]
Thanks for the update, @martab0!

**Comment by cefoo** [comment]
> From my side I'd accept this immediately but I don't know the planned usage of this file so maybe @cefoo should make a decision here.

Thanks, @zouharvi!

This file will be implemented in [machinetranslate.org](http://machinetranslate.org) similarly to the [Engines](https://machinetranslate.org/engines) or [Languages](https://machinetranslate.org/languages) pages.

**Pull request merged**
