### PR TITLE
Add list of APIs to customization and fine-tuning

### PR DESCRIPTION
**Pull request by tovmasharrison**
# Description

I added the list of APIs that support fine-tuning and overall customization to their respective pages.

### Checklist:

- [x] I have read the [contributing guidelines](contributing.md).
- [x] I have followed the [style guide](http://machinetranslate.org/style).

### CODE REVIEW

**Comment by cefoo** [comment]
Hi @tovmasharrison!

Thanks for your PR! ✨✨

Here are some comments, after a first local copy review.

1- In `customisation.md`, under "14 machine translation APIs support customisation", `Omniscien` appears several times.

image

2- A lot of MT APIs that support customisation are not listed, like `AISA` (glossary support), `Amazon Translate` (glossary support, adaptive) or `DeepL` (formality support, glossary support), to name a few.

**Comment by tovmasharrison** [comment]
> Hi @tovmasharrison!
> 
> Thanks for your PR! ✨✨
> 
> Here are some comments, after a first local copy review.
> 
> 1- In `customisation.md`, under "14 machine translation APIs support customisation", `Omniscien` appears several times.
> 
> image
> 
> 2- A lot of MT APIs that support customisation are not listed, like `AISA` (glossary support), `Amazon Translate` (glossary support, adaptive) or `DeepL` (formality support, glossary support), to name a few.

Hi @cefoo,

Thank you for pointing them out!

I have fixed those issues. Can you please check it out?

**Comment by tovmasharrison** [comment]
@bittlingmayer Done.

**Comment by cefoo** [comment]
> Hi @cefoo,
> 
> Thank you for pointing them out!
> 
> I have fixed those issues. Can you please check it out?

Hi @tovmasharrison!

Yes, I see it fixed now. Thanks!

Screenshot 2023-09-29 at 10 37 42

**Pull request merged**
