### PR TITLE
Add parallel data downloader : mtdata

### PR DESCRIPTION
**Pull request by thammegowda**
# Description

## Type of PR

- Edits _[Parallel Data]_

### Checklist:

- [X] I have read the [contributing guidelines](contributing.md).
- [X] I have followed the [style guide](http://machinetranslate.org/style).
- [X] I have made sure that the URL is not already in use.
- [X] I have cross-linked relevant articles.
- [X] I have used the UK spelling.
- [X] I have kept consistency with the structure of sister articles in the same directory.

### CODE REVIEW

**Comment by bittlingmayer** [comment]
This is a cool tool!

For Machine Translate, we have to avoid subjective stuff like "easy".

We need to think how this fits in.  Are there other such tools?  If OPUS added a text search feature, would it also qualify?

I see 2 options:
A. Add a new section (e.g. **Parallel data search**) with its own table
B. Include it in the existing table, and in the *Type* column we put *Search engine*.

**Comment by bittlingmayer** [comment]
We really can only have 1 link per listing, so it's clear to people where to go.

It's up those external properties to have a good entry point.

**Comment by thammegowda** [comment]
Hi @bittlingmayer Thanks for the comments. 

I think there are a few in the same category: 
1. Opustools (perl) https://github.com/Helsinki-NLP/OpusTools-perl 
2. Opustools (Python) https://github.com/Helsinki-NLP/OpusTools 
3.  Huggingface datasets: https://huggingface.co/datasets?task_categories=task_categories:translation&sort=downloads 

I am inclined towards including it in a separate section, maybe titled "Parallel data search and download"

**Comment by thammegowda** [comment]
Let me know what you decide, I am happy to update the pull request.

**Comment by bittlingmayer** [comment]
A separate section sounds good

I would just call it *Search and download* (since *Parallel data ___* is implied on every section here).

(We need to remove it from some of the others)

**Comment by bittlingmayer** [comment]
You could also review https://github.com/machinetranslate/machinetranslate.org/pull/292

**Comment by thammegowda** [comment]
@bittlingmayer  I have updated the pull request with the changes you have mentioned.

**Pull request merged**
