### PR TITLE
Add Alemannic (Swiss German)

### PR DESCRIPTION
**Pull request by bittlingmayer**
# Description

Add Alemannic - Swiss German, Swabian, Badian, Alsatian and some Austrian dialects

https://en.wikipedia.org/wiki/Alemannic_German

## Type of PR

- Creates the article Alemannic
- Edits *TextShuttle*

### Checklist:

- [x] I have read the [contributing guidelines](contributing.md).
- [x] I have followed the [style guide](http://machinetranslate.org/style).

### CODE REVIEW

**Comment by bittlingmayer** [comment]
Dutch is borderline in terms of typology, somewhere between Afrikaans and German, or English and German.

**Comment by cefoo** [comment]
According to [iso639-3.sil.org](https://iso639-3.sil.org), `als` is the code for `Tosk Albanian`, and `gsw` is the code for `Alemannic`.

In their website, ModernMT mentions its support for “Tosk Albanian (als)”.
[modernmt.com/api/#languages](https://modernmt.com/api/#languages)

In this PR, we are adding `Alemannic`, but not deleting `als` from the `Albanian` entry. So if we merge this PR, two things could happen:

- Either we will add ModernMT's support for `Alemannic`, which is incorrect,
- There may be a clash, having two languages with the same ISO code.

**Review by cefoo — COMMENTED** [review]
According to [iso639-3.sil.org](https://iso639-3.sil.org), `als` is the code for `Tosk Albanian`, and `gsw` is the code for `Alemannic`.

In their website, ModernMT mentions its support for “Tosk Albanian (als)”.
[modernmt.com/api/#languages](https://modernmt.com/api/#languages)

In this PR, we are adding `Alemannic`, but not deleting `als` from the `Albanian` entry. So if we merge this PR, two things could happen:

- Either we will add ModernMT's support for `Alemannic`, which is incorrect,
- There may be a clash, having two languages with the same ISO code.

**Comment by bittlingmayer** [comment]
Thank you, that's a great catch.

`als` is used by [Alemannic Wikipedia](https://als.wikipedia.org), so I had assumed it was an ISO code of some sort, but it looks like that is just an informal, grandfathered-in Wikipedia-specific convention.

I had assumed this was a clash between ISO 639-2 and 639-3, but it seems not.

Looks like TextShuttle uses `gsw` as a base code.

**Comment by cefoo** [comment]
Tested locally and works great!

**Pull request merged**
