### PR TITLE
Update statistical.md

### PR DESCRIPTION
**Pull request by luismond**
Add a recent method for enhancing SMT: paraphrase-based translation. Source: https://arxiv.org/abs/2109.15119

### CODE REVIEW

**Comment by bittlingmayer** [comment]
I'd say that paraphrasing, or any other data augmentation I can think of, is doable and common with neural too.

So probably this belongs here: https://www.machinetranslate.org/customization/training-data

**Comment by luismond** [comment]
I agree. Data augmentation should go into a sub-section of training data.

**Comment by bittlingmayer** [comment]
So is the plan to modify this PR accordingly or open a new one?

**Comment by luismond** [comment]
We will open a new PR

**Pull request closed without merging**
